Presentations/WebUIAspNetMvcCore/Areas/AdminPanel/Controllers/CarImageController.cs
using Business.Abstract;
using Entities.Dtos.CarImage;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebUIAspNetMvcCore.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class CarImageController : Controller
    {
        private ICarImageService _carImageService;

        public CarImageController(ICarImageService carImageService)
        {
            _carImageService = carImageService;
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(CarImageAddDto carImageAddDto,IFormFile[] files)
        {
            var result = _carImageService.Add(carImageAddDto, files);
            return result.Success
               ? Ok(result)
               : BadRequest(result);
        }
        public IActionResult Edit(int carImageId)
        {
            var carImage = _carImageService.GetByCarId(carImageId);
            return View(carImage);
        }

        [HttpPost]
        public IActionResult Edit(CarImageUpdateDto carImageUpdateDto, IFormFile[] files)
        {
            var result = _carImageService.Update(carImageUpdateDto, files);
            return result.Success 
                ? Ok(result) 
                : BadRequest();
        }
    }
}

Presentations/WebUIAspNetMvcCore/Areas/AdminPanel/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebUIAspNetMvcCore.Services;

namespace WebUIAspNetMvcCore.Areas.Admin.Controllers
{
    [Area("AdminPanel")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Presentations/WebUIAspNetMvcCore/Areas/AdminPanel/Views/Shared/Partial/_BreadCrumb.cshtml
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Panel</a></li>
    <li class="breadcrumb-item active">#Dinamik Sekme</li>
</ol>

Presentations/WebUIAspNetMvcCore/Areas/AdminPanel/Views/Shared/Partial/_ContentHeader.cshtml
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>#Dinamik Başlık</h1>
            </div>
            <div class="col-sm-6">
                <partial name="Partial/_BreadCrumb" />
            </div>
        </div>
    </div><!-- /.container-fluid -->

Presentations/WebUIAspNetMvcCore/Areas/AdminPanel/Views/Shared/Partial/_Footer.cshtml
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.1.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

Presentations/WebUIAspNetMvcCore/Areas/AdminPanel/Views/Shared/Partial/_Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Presentations/WebUIAspNetMvcCore/Areas/AdminPanel/Views/Shared/Partial/_Navbar.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="../../index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>     

Presentations/WebUIAspNetMvcCore/Areas/AdminPanel/Views/Shared/Partial/_Sidebar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../../index3.html" class="brand-link">
        <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Admin Paneli</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/img/user-admin.png" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a asp-controller="User" asp-action="Profile" asp-route-userId="@TempData["userId"]" class="d-block">
                    @if (TempData["userName"] != null)
                    {
                        @TempData["userName"]
                    }
                    else
                    {
                    <span class="alert alert-warning text-sm-left">Kullanıcı bulunamadı!!!</span>
                        }
                    </a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Arama..." aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a asp-controller="Dashboard" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-home"></i>
                        <p>
                            Panel
                        </p>
                    </a>

                </li>
                <li class="nav-item">
                    <a asp-controller="Car" asp-action="List" class="nav-link">
                        <i class="nav-icon fas fa-car"></i>
                        <p>
                            Arabalar
                            <span class="right badge badge-danger">Yeni</span>
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a asp-controller="Brand" asp-action="List" class="nav-link">
                        <i class="nav-icon fas fa-th-list"></i>
                        <p>
                            Markalar
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a asp-controller="Color" asp-action="List" class="nav-link">
                        <i class="nav-icon fas fa-paint-roller"></i>
                        <p>Renkler</p>
                    </a>
                </li>


                <li class="nav-item">
                    <a asp-controller="CarImage" asp-action="Add" class="nav-link">
                        <i class="nav-icon fas fa-paint-roller"></i>
                        <p>Araba Resim</p>
                    </a>
                </li>

                <li class="nav-header">AYARLAR</li>
                <li class="nav-item">
                    <a asp-controller="User" asp-action="List" class="nav-link">
                        <i class="nav-icon far fa-circle text-danger"></i>
                        <p class="text">Kullanıcılar</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="OperationClaim" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-user-tag"></i>
                        <p>
                            Roller
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="OperationClaim" asp-action="Add" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Rol Ekle</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="OperationClaim" asp-action="List" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Rol Listele</p>
                            </a>
                        </li>
                    </ul>
                </li>

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>